[deploy]
bucket = 'cfn-artifacts-luu'
region = 'us-east-1'
stack_name = 'CruddurServiceBackendFlask'

[parameters]
EnvFrontendURL = 'https://acolyteluu.cloud'
EnvBackendURL = 'https://api.acolyteluu.cloud'
DynamoDBMessagesTable = 'CruddurDynamodb-DynamoDBTable-NHRS8H7L9FYQ'