AWSTemplateFormatVersion: "2010-09-09"

Description: #Description of CFN template
  Setup ECS Cluster

Resources:
  ECSCluster: #Logical Name
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyDemoCluster
      CapacityProviders:
        - FARGATE

#Parameters:
#Metadata:
#Mappings
#Outputs: