AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Primary postgres RDS Database for the application
  - RDS instance
  - Database Security Group


Parameters:

  NetworkingStack:
    Type: String
    Description: This is our base layer of network components(VPC,subnets)
    Default: CruddurNetwork

  ClusterStack:
    Type: String
    Description: This is our base layer of compute components
    Default: CruddurCluster

  BackupRetentionPeriod:
    Type: Number
    Default: 0

  InstanceClass:
    Type: String
    Default: db.t3.micro

  InstanceIdentifier:
    Type: String
    Default: cruddur-instance

  DBName:
    Type: String
    Default: cruddur
  
  DeletionProtection:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  
  EngineVersion:
    Type: String
    Default: '15.2'

  MasterUsername:
    Type: String
  
  MasterUserPassword:
    Type: String
    NoEcho: true

Resources:
  RDSPostgresSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}RDSSG"
      GroupDescription: Public facing security group for our Cruddur ALB
      VpcId: 
        Fn::ImportValue:
          !Sub ${NetworkingStack}VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          SourceSecurityGroupId:
            Fn::ImportValue:
              !Sub ${ClusterStack}ServiceSecurityGroupId
          FromPort: 5432
          ToPort: 5432
          Description: ALB HTTP

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${AWS::StackName}DBSubnetGroup"
      DBSubnetGroupDescription: !Sub "${AWS::StackName}DBSubnetGroup"
      SubnetIds: 
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub "${NetworkingStack}PublicSubnetIds"

  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: 'Snapshot'
    UpdateReplacePolicy: 'Snapshot'
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      EnableIAMDatabaseAuthentication: false
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref InstanceClass
      DBInstanceIdentifier: !Ref InstanceIdentifier
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: !Ref DeletionProtection
      EnablePerformanceInsights: false
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt RDSPostgresSG.GroupId

#Outputs:
#  ALBSecurityGroupId:
#    Value: !GetAtt ALBSG.GroupId
#    Export:
#      Name: !Sub "${AWS::StackName}ALBSecurityGroupId"